name: Notify Discord on Merged Pull Requests

on:
  pull_request:
    types:
      - closed  # Se activa cuando el PR se cierra (mergeado o rechazado)

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged
        if: github.event.pull_request.merged == true
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "username": "GitHub Bot",
            "content": "✅ **Pull Request Mergeado!** 🎉\n🔗 [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})\n👤 Autor: ${{ github.event.pull_request.user.login }}\n🔀 Rama: ${{ github.event.pull_request.base.ref }}"
          }' "$DISCORD_WEBHOOK"
