name: Notify Discord on Push

on:
  push:
    branches:
      - main  
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "username": "GitHub Bot",
            "content": "🚀 A new push has been made to the repository! 🦾🎉\n🔗 [View Commit]('"${{ github.event.repository.html_url }}/commit/${{ github.sha }}"')"
          }' $DISCORD_WEBHOOK
